config/routes.rb
Rims::Application.routes.draw do
  post 'user_items/update'

  get "welcome/index"
  devise_for :users

  root :to => 'welcome#index'
  #root :to => redirect('/items')
  resources :items
  resources :users
end

app/models/item.rb
class Item < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  attr_accessible :description, :location, :name, :picture, :product_model_number, :vendor_part_number, :quantity, :unit_value, :vendor_url, :value, :vendor_name, :category

self.per_page = 25

belongs_to :item
belongs_to :user
after_save :update_value
protected

  def update_value
   update_column :value, (quantity * unit_value)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :items 

  attr_accessible :email, :password, :password_confirmation, :encrypted_password, :encrypted_password_confirmation, :reset_password_token, :reset_password_sent_at, :remember_created_at, :sign_in_count, :current_sign_in_at, :last_sign_in_at, :current_sign_in_ip, :last_sign_in_ip, :role, :approved

  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  def active_for_authentication? 
    super && approved? 
  end 

  def inactive_message 
    if !approved? 
      :not_approved 
    else 
      super # Use whatever other message 
    end 
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "Access denied."
    redirect_to (request.referrer || root_path)
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :authenticate_user!
  respond_to :html, :json
  # GET /items
  # GET /items.json
  def index
    @items = if params[:category].present?
      Item.where(category: params[:category])
    else
      Item.all
    end

    @items = @items.paginate(:page => params[:page])

    # respond_with(@items)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create

     @item = current_user.items.new(params[:item])
#    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        respond_with(@items)
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
#      if @item.update_columns user_id: params[:item][:user_id]
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        respond_with(@items)
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/user_items_controller.rb
class UserItemsController < ApplicationController
  before_filter :authenticate_user!
#  after_action :verify_authorized, except: [:show]

  def update
  	@item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_columns user_id: params[:item][:user_id]
      	 @item.update_columns location: params[:item][:user_id]
#      if @item.update_attributes(params[:item])
        format.html { redirect_to items_path(category: @item.category), notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        respond_with(@items)
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    if params[:approved] == "false"
      @users = User.where(approved: false)
    else
      @users = User.all
    end
    # @users = User.all
    # authorize @users
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to root_path, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    authorize @user

    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end

  private

  def secure_params
    params.require(:user).permit(:role, :approved)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/user_items_helper.rb
module UserItemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<div class="form-horizontal">
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h3>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-3 control-label" %>
    <div class="col-sm-5">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, class: "col-sm-3 control-label" %>
    <div class="col-sm-5">
      <%= f.text_area :description, class: "form-control", :rows =>10 %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :product_model_number, class: "col-sm-3 control-label" %>
    <div class="col-sm-5">
      <%= f.text_field :product_model_number, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :vendor_name, class: "col-sm-3 control-label" %>
    <div class="col-sm-5">
      <%= f.text_field :vendor_name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :vendor_part_number, class: "col-sm-3 control-label" %>
    <div class="col-sm-5">
      <%= f.text_field :vendor_part_number, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :quantity, class: "col-sm-3 control-label" %>
    <div class="col-sm-5">
      <%= f.text_field :quantity, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :vendor_url, class: "col-sm-3 control-label" %>
    <div class="col-sm-5">
      <%= f.text_field :vendor_url, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :location, class: "col-sm-3 control-label" %>
    <div class="col-sm-5">
      <%= f.text_field :location, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :unit_value, class: "col-sm-3 control-label" %>
    <div class="col-sm-5">
      <%= f.text_field :unit_value, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :category, class: "col-sm-3 control-label" %>
    <div class="col-sm-5">
      <%= f.select(:category, options_for_select([['PC', 'PC'], ['Books', 'Books'],['Devices', 'Devices']]), {}, {class: "form-control"}) %>
    </div>
  </div>


  <div class="fileinput fileinput-new" data-provides="fileinput">
    <div class="span2"  style="margin-left: 100px;">
      <div>
        <span class="btn btn-primary btn-file">
          <span class="fileinput-new">Select image</span>
          <span class="fileinput-exists">Change</span>
            <%= f.file_field :picture, :as => :file, :label => "upload a photo" %>
        </span>
        <a href="#" class="btn btn-danger fileinput-exists" data-dismiss="fileinput">Remove</a>
      </div>


    <div class="span1" style="margin-left: 185px; margin-top: -35px;">
      <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 250px; height: 200px;">
      </div>
    </div>
  </div>

</div>


  <div class="form-group">
    <div class="col-sm-offset-3 col-sm-5">
      <%= f.submit "Create Item", class: "btn btn-primary" %>
      <%= link_to 'Cancel', items_path, :class => "btn btn-danger" %>
    </div>
  </div>

<% end %>
</div>

app/views/items/edit.html.erb
<h3>Editing Item</h3>

<%= render 'form' %>

app/views/items/index.html.erb
<%# @items = Item.paginate(:page => params[:page]) %>

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Items in Inventory</h3>
  </div>

  <div class="panel-body">
    <div class="row">
      <table class="table sortable">
        <thead>
        <th>Item Name</th>
        <th><center>Imei or Model #</center></th>
        <th><center>Location</center></th>
        <th><center>Position</center></th>
    <% if current_user.admin? %>
        <th><center>Quantity</center></th>
        <th><center>Unit Value</center></th>
        <th><center>Total Value</center></th>
        <th><center>Vendor</center></th>   
        <th><center>Category</center></th>
        <th><center>User</center></th>   
        <th class="sorttable_nosort"><center>Edit/Delete</center></th>
    <% end %>    
        </thead>
        <% @items.each do |item| %>
        <tr>
          <td><%= link_to item.name, item %></td>
          <td><center><%= item.product_model_number %></center></td>
          <td><center><%= User.find(item.location).email %></center></td>  
            <% if current_user.email==item.user.email %>
              <td><center><%= button_to "Get Back", user_items_update_path(id: item.id, item: {user_id: 4})%></center></td>
            <% else%>
              <td><center><%= button_to "Take", user_items_update_path(id: item.id, item: {user_id: current_user.id})%></center></td>
           <% end %>

          
    <% if current_user.admin? %>
          <td><center><%= item.quantity %></center></td>
          <td><center><%= number_to_currency(item.unit_value, :unit => "$") %></center></td>
          <td><center><%= number_to_currency(item.value, :unit => "$") %></center></td>
          <td><center><%= item.vendor_name %></center></td>
          <td><center><%= item.category %></center></td>
          <td><center><%= User.find(item.user_id).email %></center></td>      
          <td><center><%= link_to '', edit_item_path(item), :class=>"fa fa-edit" %> |  <%= link_to content_tag(:i,nil, :class=>"fa fa-trash-o"), item, data: {confirm: 'Are you sure you want to delete this item?'}, method: :delete %></center></td>
    <% end %>

        <% end -%>

        <tfoot>
          <tr>
    <% if current_user.admin? %>
            <td><b>Totals</b></td>
            <td></td>
            <td><center><%= @items.map{|item| item.quantity}.reduce(0, :+,) %></center></td>
            <td></td>
            <td><center><%= number_to_currency(@items.map{|item| item.value}.reduce(0, :+,))%></center></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
    <% end %>
            </tr>
        </tfoot>

      </table>
    </div>

    <center>
      <div class="pagination">
        <div class="page_info">
          <%= page_entries_info @items %>
        </div>
        <%= will_paginate @items, renderer: BootstrapPagination::Rails %>
      </div>
    </center>

  </div>
</div>

app/views/items/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">New Item</h3>
  </div>

  <div class="panel-body">

<%= render 'form' %>

</div>

app/views/items/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title"><%= @item.name %></h3>
  </div>

  <div class="panel-body">

    <div class="container">

      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8"><%= image_tag(@item.picture_url, :width => "65%") if @item.picture.present? %></div>
      </div>

      <div class="row">
        <div class="col-md-2"><b>Description</b></div>
        <div class="col-md-8"><%= simple_format(@item.description) %></div>
      </div>

      <div class="row">
        <div class="col-md-2"><b>Product Model Number</b></div>
        <div class="col-md-4"><%= @item.product_model_number %></div>
      </div>

      <div class="row">
        <div class="col-md-2"><b>Vendor</b></div>
        <div class="col-md-4"><%= @item.vendor_name %></div>
      </div>

      <div class="row">
        <div class="col-md-2"><b>Vendor Part Number</b></div>
        <div class="col-md-4"><%= @item.vendor_part_number %></div>
      </div>

      <div class="row">
        <div class="col-md-2"><b>Vendor URL</b></div>
        <div class="col-md-4"><%= link_to(@item.vendor_url, @item.vendor_url, :target => "_blank") %></div>
      </div>

      <div class="row">
        <div class="col-md-2"><b>Quantity</b></div>
        <div class="col-md-4"><%= @item.quantity %></div>
      </div>

      <div class="row">
        <div class="col-md-2"><b>Unit Value</b></div>
        <div class="col-md-4"><%= number_to_currency(@item.unit_value, :unit => "$")%></div>
      </div>

      <div class="row">
        <div class="col-md-2"><b>Total Value</b></div>
        <div class="col-md-4"><%= number_to_currency(@item.value, :unit => "$") %></div>
      </div>

        <div class="row">
          <div class="col-md-2"><b>Location</b></div>
          <div class="col-md-4"><%= @item.location %></div>
        </div>

        <div class="row">
          <div class="col-md-2"></div>
          <div class="col-md-4">
            <%= link_to 'Edit', edit_item_path(@item), :class => "btn btn-primary" %>
            <%= link_to 'Delete', @item, confirm: 'Are you sure?', method: :delete, :class => "btn btn-warning" %>
            <%= link_to 'Cancel', items_path, :class => "btn btn-danger" %>
          </div>
        </div>

    </div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IM</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrap">
<%= render partial: 'shared/header' %>

<div class="container">
  <% if notice %>
  <p class="alert alert-notice"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-error"><%= alert %></p>
<% end %>

  <%= yield %>
</div>

<%= render partial: 'shared/footer' %>

</div>
</body>
</html>

app/views/shared/_footer.html.erb
<div class="container text-center">
  <div id="footer">
    <p class="muted credit"><a href="https://github.com/Molodchenko/im">Inventory Management</a></p>
  </div>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Main</a>
    </div>

  <% if user_signed_in? %>


    <!-- All Items -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><li><%= link_to 'All Items', items_path %></li> </a>
        </li>
      </ul>

    <!-- Books -->
      <ul class="nav navbar-nav">
        <li>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><li><%= link_to 'Books', items_path(category: "Books") %></li> </a>
        </li>
      </ul>

    <!-- Devices -->
      <ul class="nav navbar-nav">
        <li>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><li><%= link_to 'Devices', items_path(category: "Devices") %></li> </a>
        </li>
      </ul>

<% if current_user.admin? %>
     <!-- New Item -->
      <ul class="nav navbar-nav">
        <li>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><li><%= link_to 'New Item', new_item_path %></li> </a>
        </li>
      </ul>
<% end %>
<% end %>  

      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="items">Account <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><% if user_signed_in? %>
              <strong>&nbsp;<%= current_user.email %></strong>
              <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
              <% else %>
              <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
              <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
              <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/user_items/update.html.erb
<h1>UserItems#update</h1>
<p>Find me in app/views/user_items/update.html.erb</p>

app/views/users/_user.html.erb
<%= form_for(user) do |f| %>

<div class="container">
  <div class="row">
    <div class="span2"><%= link_to user.email, user %></div>
    <!-- <div class="span2"><%= link_to "Edit", edit_user_path(user) %></div> -->
    <div class="span3"><%= f.select(:role, User.roles.keys.map {|role| [role,role]}) %></div>
    <% if user.approved? %>
      <div class="span2">"User approved"</div>
    <% else %>
      <div class="span2">
        <%= f.label :approved, text: "Skill" do %>
          <%= f.check_box :approved, {}, true, false %>
          Need approve
        <% end %>
      </div>
    <% end %>  
    <div class="span2"><%= f.submit 'Submit', :class => 'btn btn-primary'  %></div>
    <div class="span2"><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-danger') unless user == current_user %></div>

  </div>

</div>
<% end %>
<!--
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role,role]}) %>
    <%= f.submit 'Change Role', :class => 'btn btn-primary' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-danger') unless user == current_user %>
</td>
-->

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <%= link_to "All Users", :action => "index" %>
    |
    <%= link_to "Users awaiting approval", :action => "index", :approved => "false" %>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User Details</h3>

<div class="container">

  <div class="row">
    <div class="span2"><b>Email:</b></div>
    <div class="span3"><%= @user.email if @user.email %></div>
  </div>

<div class="row">
  <div class="span2"><b>Sign In Count:</b></div>
  <div class="span3"><%= @user.sign_in_count%></div>
</div>

<div class="row">
  <div class="span2"><b>Last IP:</b></div>
  <div class="span3"><%= @user.last_sign_in_ip%></div>
</div>

<div class="row">
  <div class="span2"><b>Last Sign In:</b></div>
  <div class="span3"><%= @user.last_sign_in_at%></div>
</div>

<div class="row">
  <div class="span2"><b>User Created:</b></div>
  <div class="span3"><%= @user.created_at%></div>
</div>

<div class="row">
  <div class="span2"><b>User Updated:</b></div>
  <div class="span3"><%= @user.updated_at%></div>
</div>

</div>
<br />
<%= link_to 'Back', users_path, :class => "btn btn-danger" %>

<br /><br />

app/views/welcome/index.html.erb
<div class="jumbotron">
  <div class="row">
    <div class="span3">
      <!-- <img alt="Logo" class="logo" src="Image"> -->
    </div>

  <div class="span7">
    <h2>Inventory Management</h2>
  </div>

  </div>
</div>